# Generated by Django 5.0.6 on 2024-07-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='videos_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.IntegerField()),
                ('video_name', models.CharField(max_length=50)),
                ('video_extension', models.CharField(max_length=5)),
                ('video_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='videos_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.IntegerField()),
                ('id_user', models.IntegerField()),
            ],
        ),
    ]
