# Generated by Django 5.0.6 on 2024-07-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos_data',
            name='video_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
