# Generated by Django 5.0.6 on 2024-07-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_videos_data_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos_users',
            name='id_user',
            field=models.CharField(max_length=10),
        ),
    ]
