# Generated by Django 5.0.6 on 2024-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0003_alter_videos_users_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_video', models.IntegerField()),
            ],
        ),
    ]
