# Generated by Django 5.0.6 on 2024-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0004_video_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_number',
            name='id_user',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_number',
            name='nombre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
